export type AutonomousSystem = {
  id: string;
  name: string;
  description: string;
  category: "marketing" | "devops" | "payroll" | "compliance" | "investment" | "governance" | "insurance" | "escrow" | "liquidity" | "bridge" | "whitelist" | "reporting" | "staking" | "communication" | "data" | "backup" | string;
  status: "active" | "idle" | "restricted";
  goal?: string;
  budget?: number;
  kpiTargets?: { name: string; target: number; unit: string; isHigherBetter: boolean }[];
  customPrompt?: string;
  isCustom?: boolean;
};

export const AUTONOMOUS_SYSTEMS: AutonomousSystem[] = [
  {
    id: "marketing",
    name: "Marketing Agent",
    description: "Autonomous ad spend and vendor payments for growth campaigns.",
    category: "marketing",
    status: "active",
    goal: "Maximize Q2 marketing ROI with targeted vendor payments",
    budget: 500,
    kpiTargets: [
      { name: "ROI", target: 2.0, unit: "x", isHigherBetter: true },
      { name: "Vendor Diversity", target: 3, unit: "count", isHigherBetter: true },
      { name: "Max Single Payment", target: 100, unit: "usdc", isHigherBetter: false },
    ],
  },
  {
    id: "devops",
    name: "DevOps Agent",
    description: "Infrastructure provisioning and cloud vendor settlements.",
    category: "devops",
    status: "active",
    goal: "Maintain 99.9% uptime with cost-efficient infrastructure",
    budget: 300,
    kpiTargets: [
      { name: "Uptime", target: 99.9, unit: "%", isHigherBetter: true },
      { name: "Max Single Payment", target: 50, unit: "usdc", isHigherBetter: false },
      { name: "Vendor Lock-in", target: 70, unit: "%", isHigherBetter: false },
    ],
  },
  {
    id: "payroll",
    name: "Payroll Agent",
    description: "Scheduled contractor payouts with compliance guardrails.",
    category: "payroll",
    status: "active",
    goal: "Process contractor payments on time, every time",
    budget: 200,
    kpiTargets: [
      { name: "On-time Payments", target: 100, unit: "%", isHigherBetter: true },
      { name: "Contractors Paid", target: 5, unit: "count", isHigherBetter: true },
    ],
  },
  {
    id: "legal",
    name: "Legal Agent",
    description: "Regulatory compliance, contract review, and legal settlements.",
    category: "legal",
    status: "active",
    goal: "Ensure all transactions comply with regulatory requirements",
    budget: 150,
    kpiTargets: [
      { name: "Compliance Rate", target: 100, unit: "%", isHigherBetter: true },
      { name: "Contracts Reviewed", target: 10, unit: "count", isHigherBetter: true },
      { name: "Violations", target: 0, unit: "count", isHigherBetter: false },
    ],
  },
  {
    id: "analytics",
    name: "Analytics Agent",
    description: "Generate reports, track ROI, and provide data-driven insights.",
    category: "analytics",
    status: "active",
    goal: "Provide actionable insights for treasury optimization",
    budget: 100,
    kpiTargets: [
      { name: "Reports Generated", target: 12, unit: "count", isHigherBetter: true },
      { name: "Insights Accuracy", target: 95, unit: "%", isHigherBetter: true },
      { name: "Cost Savings", target: 50, unit: "usdc", isHigherBetter: true },
    ],
  },
  {
    id: "security",
    name: "Security Agent",
    description: "Monitor suspicious activity, detect fraud, and protect treasury.",
    category: "security",
    status: "active",
    goal: "Detect and prevent fraudulent transactions before execution",
    budget: 250,
    kpiTargets: [
      { name: "Fraud Detected", target: 100, unit: "%", isHigherBetter: true },
      { name: "False Positives", target: 5, unit: "%", isHigherBetter: false },
      { name: "Response Time", target: 30, unit: "seconds", isHigherBetter: false },
    ],
  },
  {
    id: "treasury",
    name: "Treasury Agent",
    description: "Cash flow management, liquidity optimization, and reserve maintenance.",
    category: "treasury",
    status: "active",
    goal: "Maintain optimal liquidity while maximizing yield",
    budget: 1000,
    kpiTargets: [
      { name: "Liquidity Ratio", target: 20, unit: "%", isHigherBetter: true },
      { name: "Yield", target: 5, unit: "%", isHigherBetter: true },
      { name: "Reserve Utilization", target: 80, unit: "%", isHigherBetter: false },
    ],
  },
  {
    id: "vendor",
    name: "Vendor Agent",
    description: "Manage vendor relationships, negotiate contracts, and track performance.",
    category: "vendor",
    status: "active",
    goal: "Optimize vendor costs while maintaining quality",
    budget: 400,
    kpiTargets: [
      { name: "Cost Reduction", target: 15, unit: "%", isHigherBetter: true },
      { name: "Vendor Score", target: 85, unit: "score", isHigherBetter: true },
      { name: "Contract Compliance", target: 100, unit: "%", isHigherBetter: true },
    ],
  },
  {
    id: "rnd",
    name: "R&D Agent",
    description: "Research and development funding, innovation grants, and tech investments.",
    category: "rnd",
    status: "idle",
    goal: "Fund innovative projects with high potential ROI",
    budget: 350,
    kpiTargets: [
      { name: "Projects Funded", target: 5, unit: "count", isHigherBetter: true },
      { name: "Success Rate", target: 40, unit: "%", isHigherBetter: true },
      { name: "Innovation Score", target: 80, unit: "score", isHigherBetter: true },
    ],
  },
  {
    id: "support",
    name: "Support Agent",
    description: "Customer support operations, refund processing, and issue resolution.",
    category: "support",
    status: "active",
    goal: "Resolve customer issues quickly and cost-effectively",
    budget: 150,
    kpiTargets: [
      { name: "Resolution Rate", target: 95, unit: "%", isHigherBetter: true },
      { name: "Avg Resolution Time", target: 24, unit: "hours", isHigherBetter: false },
      { name: "Customer Satisfaction", target: 90, unit: "%", isHigherBetter: true },
    ],
  },
  {
    id: "sales",
    name: "Sales Agent",
    description: "Sales operations, commission payouts, and revenue tracking.",
    category: "sales",
    status: "active",
    goal: "Maximize revenue while maintaining healthy margins",
    budget: 300,
    kpiTargets: [
      { name: "Revenue", target: 5000, unit: "usdc", isHigherBetter: true },
      { name: "Commission Payouts", target: 500, unit: "usdc", isHigherBetter: false },
      { name: "Win Rate", target: 30, unit: "%", isHigherBetter: true },
    ],
  },
  {
    id: "procurement",
    name: "Procurement Agent",
    description: "Purchase orders, supplier management, and inventory optimization.",
    category: "procurement",
    status: "idle",
    goal: "Procure goods and services at optimal prices",
    budget: 600,
    kpiTargets: [
      { name: "Cost Savings", target: 20, unit: "%", isHigherBetter: true },
      { name: "Order Accuracy", target: 98, unit: "%", isHigherBetter: true },
      { name: "Delivery Time", target: 5, unit: "days", isHigherBetter: false },
    ],
  },
  {
    id: "risk",
    name: "Risk Agent",
    description: "Risk assessment, portfolio diversification, and hedging strategies.",
    category: "risk",
    status: "active",
    goal: "Minimize treasury risk while maintaining growth",
    budget: 200,
    kpiTargets: [
      { name: "Risk Score", target: 30, unit: "score", isHigherBetter: false },
      { name: "Diversification", target: 70, unit: "%", isHigherBetter: true },
      { name: "Hedging Coverage", target: 50, unit: "%", isHigherBetter: true },
    ],
  },
  {
    id: "compliance",
    name: "Compliance Agent",
    description: "KYC/AML checks, regulatory reporting, and sanctions screening.",
    category: "compliance",
    status: "active",
    goal: "Ensure 100% regulatory compliance across all transactions",
    budget: 200,
    kpiTargets: [
      { name: "KYC Pass Rate", target: 100, unit: "%", isHigherBetter: true },
      { name: "AML Flags Resolved", target: 100, unit: "%", isHigherBetter: true },
      { name: "Regulatory Score", target: 95, unit: "score", isHigherBetter: true },
    ],
  },
  {
    id: "investment",
    name: "Investment Agent",
    description: "DeFi yield farming, staking strategies, and portfolio optimization.",
    category: "investment",
    status: "active",
    goal: "Maximize yield while maintaining acceptable risk levels",
    budget: 800,
    kpiTargets: [
      { name: "APY", target: 12, unit: "%", isHigherBetter: true },
      { name: "Impermanent Loss", target: 2, unit: "%", isHigherBetter: false },
      { name: "Protocol Diversity", target: 5, unit: "count", isHigherBetter: true },
    ],
  },
  {
    id: "governance",
    name: "Governance Agent",
    description: "DAO governance participation, proposal voting, and delegation management.",
    category: "governance",
    status: "idle",
    goal: "Actively participate in governance to protect treasury interests",
    budget: 100,
    kpiTargets: [
      { name: "Proposals Voted", target: 90, unit: "%", isHigherBetter: true },
      { name: "Voting Power Used", target: 80, unit: "%", isHigherBetter: true },
      { name: "Delegation Score", target: 95, unit: "score", isHigherBetter: true },
    ],
  },
  {
    id: "insurance",
    name: "Insurance Agent",
    description: "Protocol insurance coverage, claim management, and risk mitigation.",
    category: "insurance",
    status: "active",
    goal: "Maintain adequate coverage for all treasury exposures",
    budget: 250,
    kpiTargets: [
      { name: "Coverage Ratio", target: 80, unit: "%", isHigherBetter: true },
      { name: "Claims Filed", target: 100, unit: "%", isHigherBetter: true },
      { name: "Premium Cost", target: 200, unit: "usdc", isHigherBetter: false },
    ],
  },
  {
    id: "escrow",
    name: "Escrow Agent",
    description: "Multi-sig escrow operations, milestone-based releases, and dispute resolution.",
    category: "escrow",
    status: "active",
    goal: "Secure all high-value transactions with escrow protection",
    budget: 500,
    kpiTargets: [
      { name: "Escrow Success Rate", target: 100, unit: "%", isHigherBetter: true },
      { name: "Avg Release Time", target: 48, unit: "hours", isHigherBetter: false },
      { name: "Disputes Resolved", target: 100, unit: "%", isHigherBetter: true },
    ],
  },
  {
    id: "liquidity",
    name: "Liquidity Agent",
    description: "DEX liquidity provision, pool management, and impermanent loss mitigation.",
    category: "liquidity",
    status: "active",
    goal: "Optimize liquidity provision across DEXes for maximum fees",
    budget: 600,
    kpiTargets: [
      { name: "LP Fees Earned", target: 500, unit: "usdc", isHigherBetter: true },
      { name: "Pool Utilization", target: 75, unit: "%", isHigherBetter: true },
      { name: "IL Protection", target: 90, unit: "%", isHigherBetter: true },
    ],
  },
  {
    id: "bridge",
    name: "Bridge Agent",
    description: "Cross-chain asset transfers, bridge monitoring, and multi-chain treasury management.",
    category: "bridge",
    status: "active",
    goal: "Enable seamless cross-chain operations with minimal fees",
    budget: 300,
    kpiTargets: [
      { name: "Bridge Success Rate", target: 100, unit: "%", isHigherBetter: true },
      { name: "Avg Bridge Time", target: 10, unit: "minutes", isHigherBetter: false },
      { name: "Fee Savings", target: 30, unit: "%", isHigherBetter: true },
    ],
  },
  {
    id: "whitelist",
    name: "Whitelist Agent",
    description: "Address whitelist management, vendor verification, and access control.",
    category: "whitelist",
    status: "active",
    goal: "Maintain secure and verified vendor whitelist",
    budget: 50,
    kpiTargets: [
      { name: "Whitelist Accuracy", target: 100, unit: "%", isHigherBetter: true },
      { name: "Verification Time", target: 24, unit: "hours", isHigherBetter: false },
      { name: "Fraud Prevention", target: 99, unit: "%", isHigherBetter: true },
    ],
  },
  {
    id: "reporting",
    name: "Reporting Agent",
    description: "Financial reporting, tax documentation, and audit trail generation.",
    category: "reporting",
    status: "active",
    goal: "Generate accurate reports for all stakeholders",
    budget: 100,
    kpiTargets: [
      { name: "Reports Generated", target: 24, unit: "count", isHigherBetter: true },
      { name: "Accuracy Rate", target: 99, unit: "%", isHigherBetter: true },
      { name: "On-time Delivery", target: 100, unit: "%", isHigherBetter: true },
    ],
  },
  {
    id: "staking",
    name: "Staking Agent",
    description: "Staking rewards optimization, validator management, and compound strategies.",
    category: "staking",
    status: "active",
    goal: "Maximize staking rewards across multiple protocols",
    budget: 400,
    kpiTargets: [
      { name: "Staking APY", target: 8, unit: "%", isHigherBetter: true },
      { name: "Validator Uptime", target: 99, unit: "%", isHigherBetter: true },
      { name: "Compound Frequency", target: 7, unit: "days", isHigherBetter: false },
    ],
  },
  {
    id: "communication",
    name: "Communication Agent",
    description: "Stakeholder notifications, treasury updates, and automated reporting.",
    category: "communication",
    status: "idle",
    goal: "Keep all stakeholders informed with timely updates",
    budget: 75,
    kpiTargets: [
      { name: "Notifications Sent", target: 100, unit: "%", isHigherBetter: true },
      { name: "Response Time", target: 1, unit: "hours", isHigherBetter: false },
      { name: "Stakeholder Satisfaction", target: 90, unit: "%", isHigherBetter: true },
    ],
  },
  {
    id: "data",
    name: "Data Agent",
    description: "On-chain data pipelines, analytics infrastructure, and market intelligence.",
    category: "data",
    status: "active",
    goal: "Provide real-time market data and analytics for all agents",
    budget: 150,
    kpiTargets: [
      { name: "Data Freshness", target: 5, unit: "minutes", isHigherBetter: false },
      { name: "Pipeline Uptime", target: 99.9, unit: "%", isHigherBetter: true },
      { name: "Sources Integrated", target: 10, unit: "count", isHigherBetter: true },
    ],
  },
  {
    id: "backup",
    name: "Backup Agent",
    description: "Data backup, disaster recovery, and business continuity planning.",
    category: "backup",
    status: "active",
    goal: "Ensure zero data loss with automated backup and recovery",
    budget: 100,
    kpiTargets: [
      { name: "Backup Success Rate", target: 100, unit: "%", isHigherBetter: true },
      { name: "Recovery Time", target: 4, unit: "hours", isHigherBetter: false },
      { name: "RPO", target: 1, unit: "hours", isHigherBetter: false },
    ],
  },
];
